global:
  # The key of group list in OIDC user info
  groupKey: 'cognito:groups'


customizations:
  - # Regex to select user group to apply config to
    groupSelector: '.*'
    action: default
    navigation: default
    list: default
    edit: default
    link: default

list:
  default:
    nodes:
      - label: "Name"
        key: '$.metadata.name'
        width: 3
      - label: "Ready"
        key: '$.status.conditions[?(@.type=="Ready")].status'
      - label: "Age"
        key: '$.metadata.creationTimestamp'
        type: duration
      - label: Version
        key: '$.status.nodeInfo.kubeletVersion'
        width: 2
        selectable: true
    pods:
      - label: 'Name'
        key: '$.metadata.name'
        width: 4
      - label: 'Status'
        key: '$.status.phase'
        type: 'badge'
        width: 1
      - label: 'Age'
        key: '$.metadata.creationTimestamp'
        type: duration
      - label: 'Node'
        key: '$.spec.nodeName'
        width: 5
        selectable: true
      - label: 'Namespace'
        key: '$.metadata.namespace'
        width: 3
        selectable: true
    apps/deployments:
      - label: 'Name'
        key: '$.metadata.name'
        width: 4
      - label: 'Current'
        key: '$.status.replicas'
      - label: 'Desired'
        key: '$.spec.replicas'
      - label: 'Age'
        key: '$.metadata.creationTimestamp'
        type: duration
    helm.toolkit.fluxcd.io/helmreleases:
      - label: 'Name'
        key: '$.metadata.name'
        width: 4
      - label: 'Age'
        key: '$.metadata.creationTimestamp'
        type: duration
      - label: 'Ready'
        key: '$.status.conditions[?(@.type=="Ready")].status'
    source.toolkit.fluxcd.io/helmcharts:
      - label: 'Name'
        key: '$.metadata.name'
        width: 4
      - label: 'Chart'
        key: '$.spec.chart'
        selectable: true
        width: 3
      - label: 'Version'
        key: '$.spec.version'
        selectable: true
      - label: 'Age'
        key: '$.metadata.creationTimestamp'
        type: duration
      - label: 'Ready'
        key: '$.status.conditions[?(@.type=="Ready")].status'
    source.toolkit.fluxcd.io/helmrepositories:
      - label: 'Name'
        key: '$.metadata.name'
        width: 2
      - label: 'URL'
        key: '$.spec.url'
        width: 4
      - label: 'Age'
        key: '$.metadata.creationTimestamp'
        type: duration
      - label: 'Ready'
        key: '$.status.conditions[?(@.type=="Ready")].status'
    kustomize.toolkit.fluxcd.io/kustomizations:
      - label: 'Name'
        key: '$.metadata.name'
        width: 4
      - label: 'Age'
        key: '$.metadata.creationTimestamp'
        type: duration
      - label: 'Ready'
        key: '$.status.conditions[?(@.type=="Ready")].status'
    source.toolkit.fluxcd.io/gitrepositories:
      - label: 'Name'
        key: '$.metadata.name'
        width: 2
      - label: 'URL'
        key: '$.spec.url'
        width: 4
      - label: 'Age'
        key: '$.metadata.creationTimestamp'
        type: duration
      - label: 'Ready'
        key: '$.status.conditions[?(@.type=="Ready")].status'

edit:
  default:
    '*':
      # - label: 'Name'
      #   key: '$.metadata.name'
      #   type: fields
      # - label: 'Name'
      #   key: '$.metadata.namespace'
      #   type: fields
      - label: 'Annotations'
        key: '$.metadata.annotations'
        type: fields
      - label: 'Labels'
        key: '$.metadata.labels'
        type: fields
      - label: 'Status'
        key: '$.status'
        subresource: status
    configmaps:
      - label: 'Metadata'
        key: '$.metadata'
      - label: 'Data'
        key: '$.data'
        type: fields
    secrets:
      - label: 'Metadata'
        key: '$.metadata'
      - label: 'Data'
        key: '$.data'
        type: base64fields


link:
  default:
    pods:
      - key: '$.spec.nodeName'
        target: 'nodes/name'

action:
  default:
    get:
      include:
        - '*'
      exclude: []
    update:
      include:
        - '*'
      exclude: []
    delete:
      include:
        - '*'
      exclude: []
    create:
      include:
        - '*'
      exclude: []
    cordon:
      include:
        - 'nodes'
      exclude: 
        - '*' 
    drain: 
      include:
        - 'nodes'
      exclude:
        - '*' 
    exec:
      include:
        - 'pods'
      exclude: 
        - '*' 
    logs: 
      include:
        - 'pods'
      exclude: 
        - '*' 
    sync:
      include:
      - "helm.toolkit.fluxcd.io/helmreleases"
      - "kustomize.toolkit.fluxcd.io/kustomizations"
      - "source.toolkit.fluxcd.io/gitrepositories"
      - 'external-secrets.io/externalsecrets'
      - 'external-secrets.io/pushsecrets'
      exclude: 
        - '*' 
    pause:
      include:
        - "helm.toolkit.fluxcd.io/helmreleases"
        - "kustomize.toolkit.fluxcd.io/kustomizations"
        - "source.toolkit.fluxcd.io/gitrepositories"
      exclude: 
        - '*' 
    resume:
      include:
        - "helm.toolkit.fluxcd.io/helmreleases"
        - "kustomize.toolkit.fluxcd.io/kustomizations"
        - "source.toolkit.fluxcd.io/gitrepositories"
      exclude: 
        - '*' 

navigation:
  default:
    otherResources: 
      enabled: true
      label: 'Other'
    menuItems:
      - label: 'Nodes'
        icon: "https://raw.githubusercontent.com/kubernetes/community/refs/heads/master/icons/svg/infrastructure_components/unlabeled/node.svg"
        subItems:
          - label: 'NodeClaims'
            route: 'karpenter.sh/nodeclaims'
          - label: 'Nodes'
            route: 'nodes'
          - label: 'NodePools'
            route: 'karpenter.sh/nodepools'
          - label: 'EC2NodeClass'
            route: 'karpenter.k8s.aws/ec2nodeclasses'
      - label: 'Workload'
        icon: "https://raw.githubusercontent.com/kubernetes/community/refs/heads/master/icons/svg/resources/unlabeled/pod.svg"
        subItems:
          - label: 'Pods'
            route: 'pods'
          - label: 'Deployments'
            route: 'apps/deployments'
          - label: 'StatefulSets'
            route: 'apps/statefulsets'
          - label: 'DaemonSets'
            route: 'apps/daemonsets'
          - label: 'ReplicaSets'
            route: 'apps/replicasets'
          - label: 'ReplicationController'
            route: 'replicationcontrollers'
          - label: 'Jobs'
            route: 'batch/jobs'
          - label: 'CronJobs'
            route: 'batch/cronjobs'
      - label: 'Config'
        icon: "https://raw.githubusercontent.com/kubernetes/community/refs/heads/master/icons/svg/resources/unlabeled/cm.svg"
        subItems:
          - label: 'ConfigMaps'
            route: 'configmaps'
          - label: 'Secrets'
            route: 'secrets'
          - label: 'ResourceQuotas'
            route: 'resourcequotas'
          - label: 'LimitRanges'
            route: 'limitranges'
          - label: 'HorizontalPodAutoscalers'
            route: 'autoscaling/horizontalpodautoscalers'
          - label: 'PodDisruptionBudgets'
            route: 'policy/poddisruptionbudgets'
          - label: 'PriorityClasses'
            route: 'scheduling.k8s.io/priorityclasses'
          - label: 'RuntimeClasses'
            route: 'node.k8s.io/runtimeclasses'
          - label: 'Lease'
            route: 'coordination.k8s.io/leases'
          - label: 'MutatingWebhookConfigurations'
            route: 'admissionregistration.k8s.io/mutatingwebhookconfigurations'
          - label: 'ValidatingWebhookConfigurations'
            route: 'admissionregistration.k8s.io/validatingwebhookconfigurations'
          - label: 'CustomResourceDefinitions'
            route: 'apiextensions.k8s.io/customresourcedefinitions'
          - label: 'PodSecurityPolicies'
            route: 'policy/podsecuritypolicies'
      - label: 'Network'
        icon: "https://raw.githubusercontent.com/kubernetes/community/refs/heads/master/icons/svg/resources/unlabeled/svc.svg"
        subItems:
          - label: 'Services'
            route: 'services'
          - label: 'Endpoints'
            route: 'endpoints'
          - label: 'Ingresses'
            route: 'networking.k8s.io/ingresses'
          - label: 'IngresClasses'
            route: 'networking.k8s.io/ingressclasses'
      - label: 'Storage'
        icon: "https://raw.githubusercontent.com/kubernetes/community/refs/heads/master/icons/svg/resources/unlabeled/pvc.svg"
        subItems:
          - label: 'PersistentVolumeClaims'
            route: 'persistentvolumeclaims'
          - label: 'PersistentVolumes'
            route: 'persistentvolumes'
          - label: 'StorageClasses'
            route: 'storage.k8s.io/storageclasses'
      - label: 'Access Control'
        icon: "https://raw.githubusercontent.com/kubernetes/community/refs/heads/master/icons/svg/resources/unlabeled/sa.svg"
        subItems:
          - label: 'ServiceAccounts'
            route: 'serviceaccounts'
          - label: 'Roles'
            route: 'rbac.authorization.k8s.io/roles'
          - label: 'RoleBindings'
            route: 'rbac.authorization.k8s.io/rolebindings'
          - label: 'ClusterRoles'
            route: 'rbac.authorization.k8s.io/clusterroles'
      - label: 'FluxCD'
        icon: "https://raw.githubusercontent.com/fluxcd/website/refs/heads/main/assets/icons/logo.svg"
        subItems:
          - label: 'HelmReleases'
            route: 'helm.toolkit.fluxcd.io/helmreleases'
          - label: 'HelmCharts'
            route: 'source.toolkit.fluxcd.io/helmcharts'
          - label: 'HelmRepositories'
            route: 'source.toolkit.fluxcd.io/helmrepositories'
          - label: 'Kustomizations'
            route: 'kustomize.toolkit.fluxcd.io/kustomizations'
          - label: 'GitRepositories'
            route: 'source.toolkit.fluxcd.io/gitrepositories'
      - label: 'External Secrets'
        icon: "https://raw.githubusercontent.com/external-secrets/external-secrets/refs/heads/main/docs/pictures/eso-round-logo.svg"
        subItems:
          - label: 'External Secrets'
            route: 'external-secrets.io/externalsecrets'
          - label: 'Cluster External Secrets'
            route: 'external-secrets.io/clusterexternalsecrets'
          - label: 'Push Secrets'
            route: 'external-secrets.io/pushsecrets'
          - label: 'Secret Stores'
            route: 'external-secrets.io/secretstores'
          - label: 'Cluster Secret Stores'
            route: 'external-secrets.io/clustersecretstores'
      - label: 'Homer'
        icon: "https://raw.githubusercontent.com/bastienwirtz/homer/refs/heads/main/public/assets/icons/logo.svg"
        subItems:
          - label: 'Homer Services'
            route: 'homer.bananaops.io/homerservices'
      - label: 'Velero'
        icon: ""
        subItems:
          - label: 'Schedules'
            route: 'velero.io/schedules'
          - label: 'Backups'
            route: 'velero.io/backups'
      - label: 'Chaos Mesh'
        icon: "https://raw.githubusercontent.com/chaos-mesh/chaos-mesh/refs/heads/master/ui/app/src/images/logo-mini.svg"
        subItems:
          - label: 'Physical Machines'
            route: 'chaos-mesh.org/physicalmachines'
          - label: 'AWS Chaos'
            route: 'chaos-mesh.org/awschaos'
          - label: 'Network Chaos'
            route: 'chaos-mesh.org/networkchaos'
          - label: 'Status Checks'
            route: 'chaos-mesh.org/statuschecks'
          - label: 'Kernel Chaos'
            route: 'chaos-mesh.org/kernelchaos'
          - label: 'JVM Chaos'
            route: 'chaos-mesh.org/jvmchaos'
          - label: 'Workflow Nodes'
            route: 'chaos-mesh.org/workflownodes'
          - label: 'I/O Chaos'
            route: 'chaos-mesh.org/iochaos'
          - label: 'Pod I/O Chaos'
            route: 'chaos-mesh.org/podiochaos'
          - label: 'Pod Network Chaos'
            route: 'chaos-mesh.org/podnetworkchaos'
          - label: 'Physical Machine Chaos'
            route: 'chaos-mesh.org/physicalmachinechaos'
          - label: 'HTTP Chaos'
            route: 'chaos-mesh.org/httpchaos'
          - label: 'Time Chaos'
            route: 'chaos-mesh.org/timechaos'
          - label: 'Stress Chaos'
            route: 'chaos-mesh.org/stresschaos'
          - label: 'DNS Chaos'
            route: 'chaos-mesh.org/dnschaos'
          - label: 'Pod HTTP Chaos'
            route: 'chaos-mesh.org/podhttpchaos'
          - label: 'Workflows'
            route: 'chaos-mesh.org/workflows'
          - label: 'Block Chaos'
            route: 'chaos-mesh.org/blockchaos'
          - label: 'Schedules'
            route: 'chaos-mesh.org/schedules'
      - label: 'Namespace'
        icon: "https://raw.githubusercontent.com/kubernetes/community/refs/heads/master/icons/svg/resources/unlabeled/ns.svg"
        route: 'namespaces'
      - label: 'Event'
        icon: '57918'
        route: 'events'
