{{- range $name,$list := .Values.listViews }}
---
apiVersion: schwifty.pewty.fr/v1
kind: ListView
metadata:
  labels:
    {{- include "schwifty.labels" $ | nindent 4 }}
  name: {{ $name }}
spec:
  {{- toYaml $list | nindent 2 }}
{{- end}}
