{{- range $name,$navigation := .Values.navigations }}
---
apiVersion: schwifty.pewty.fr/v1
kind: Navigation
metadata:
  labels:
    {{- include "schwifty.labels" $ | nindent 4 }}
  name: {{ $name }}
spec:
  {{- toYaml $navigation | nindent 2 }}
{{- end}}
