{{- range $name,$customization := .Values.customizations }}
---
apiVersion: schwifty.pewty.fr/v1
kind: Customization
metadata:
  labels:
    {{- include "schwifty.labels" $ | nindent 4 }}
  name: {{ $name }}
spec:
  {{- toYaml $customization | nindent 2 }}
{{- end}}
