{{ if .Values.config.api.authentication.basic.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.api.authentication.basic.secretRef.name }}
  labels:
    {{- include "schwifty.labels" $ | nindent 4 }}
type: Opaque
data:
  users: |
    {{- tpl (toJson .Values.users) . | b64enc | nindent 4 }}
{{ end -}}
