---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "schwifty.fullname" . }}
  labels:
    {{- include "schwifty.labels" $ | nindent 4 }}
type: Opaque
data:
  config.yaml: |
    {{- tpl (toYaml .Values.config) . | b64enc | nindent 4 }}
