{{- if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "schwifty.serviceAccountName" . }}
  labels:
    {{- include "schwifty.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{-  tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }}
